### ISSUE TITLE
2022年的节假日出来了，获取不到

### ISSUE THREAD

**Issue by realzuojianxiang** [longweiqiang/get_holiday_cn#1]
2022年的节假日出来了，获取不到，麻烦更新一下？谢谢

**Comment by jupitersh** [comment]
还是没法使用

**Comment by jupitersh** [comment]
get_holiday_cn.client.YearKeyError: 年份异常，年份入参为：2023，请检查入参

**Comment by longweiqiang** [comment]
> get_holi.client.YearError: 年份异常，入参日23，请检查入参

有截图吗？我这试了23年的是可以的

**Comment by longweiqiang** [comment]
> get_holiday_cn.client.YearKeyError: 年份异常，年份入参为：2023，请检查入参

如果在2021年期间请求，那最大的年份入参是2022年，如果这时候你入参是2023年，就会提示年份异常。不清楚你具体的代码实现，如果依然有问题，可以新开issues附带截图
